import { EducatorObject } from "../types/educator";
import { AnnouncementObject } from "../types/interfaces";

export const userStudent = {
  type: "student",
  name: "Mugisha Precieux",
  email: "precieuxmugisha@gmail.com",
  profileImage:
    "http://res.cloudinary.com/dyrneab5i/image/upload/v1647457738/tpkcgy3l9penta3gwb3a.png",
};

export const userTeacher = {
  type: "educator",
  name: "HABANABASHAKA Jean Damascene",
  email: "damascene10@gmail.com",
  profileImage:
    "http://res.cloudinary.com/dyrneab5i/image/upload/v1647457738/tpkcgy3l9penta3gwb3a.png",
};

export const userParent = {
  type: "parent",
  name: "ISHIMWE Vainqueur",
  email: "ishimvainqueur@gmail.com",
  profileImage:
    "http://res.cloudinary.com/dyrneab5i/image/upload/v1647457738/tpkcgy3l9penta3gwb3a.png",
};

export const studentsDisplay: any = {
  year_2: [
    {
      "First Name": "IGIRIMPUHWE",
      "Last Name": "Aime",
      "Code/ID": "RCA0201NSZ",
      "Year/Grade": 2,
      Class: "C",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834845",
    },
    {
      "First Name": "Biziyaremye",
      "Last Name": "Henriette",
      "Code/ID": "RCA0202JIZ",
      "Year/Grade": 2,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834846",
    },
    {
      "First Name": "Burigo",
      "Last Name": "Aldo Jabes",
      "Code/ID": "RCA0203NMZ",
      "Year/Grade": 2,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834847",
    },
    {
      "First Name": "Bwiza",
      "Last Name": "Nina",
      "Code/ID": "RCA0204ZUR",
      "Year/Grade": 2,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834848",
    },
    {
      "First Name": "Byiringiro",
      "Last Name": "Saad",
      "Code/ID": "RCA0205HDV",
      "Year/Grade": 2,
      Class: "C",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834849",
    },
    {
      "First Name": "DABAGIRE",
      "Last Name": "Valens",
      "Code/ID": "RCA0206AKB",
      "Year/Grade": 2,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834850",
    },
    {
      "First Name": "Dufitumukiza",
      "Last Name": "Emmanuel",
      "Code/ID": "RCA0207RVY",
      "Year/Grade": 2,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834851",
    },
    {
      "First Name": "Dukunde Irakoze",
      "Last Name": "Acele Happy",
      "Code/ID": "RCA0208ZAK",
      "Year/Grade": 2,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834852",
    },
    {
      "First Name": "Dushime",
      "Last Name": "Grace Fidele",
      "Code/ID": "RCA0209ZNK",
      "Year/Grade": 2,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834853",
    },
    {
      "First Name": "Dushime",
      "Last Name": "Bill Benon",
      "Code/ID": "RCA0210GNU",
      "Year/Grade": 2,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834854",
    },
    {
      "First Name": "Dushimimana",
      "Last Name": "Sandrine",
      "Code/ID": "RCA0211ZXU",
      "Year/Grade": 2,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834855",
    },
    {
      "First Name": "Gashugi Muhimpundu",
      "Last Name": "Aderline",
      "Code/ID": "RCA0212RKE",
      "Year/Grade": 2,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834856",
    },
    {
      "First Name": "Gikundiro Larissa",
      "Last Name": "Teta",
      "Code/ID": "RCA0213KKA",
      "Year/Grade": 2,
      Class: "C",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834857",
    },
    {
      "First Name": "Girishya",
      "Last Name": "Fiat Bruno",
      "Code/ID": "RCA0214KTL",
      "Year/Grade": 2,
      Class: "C",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834858",
    },
    {
      "First Name": "Igihozo Nyituriki",
      "Last Name": "Marie Colombe",
      "Code/ID": "RCA0215HDC",
      "Year/Grade": 2,
      Class: "C",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834859",
    },
    {
      "First Name": "Ihozo",
      "Last Name": "Marie Honnette",
      "Code/ID": "RCA0216EBG",
      "Year/Grade": 2,
      Class: "C",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834860",
    },
    {
      "First Name": "Imanzi",
      "Last Name": "Yannick Kenny",
      "Code/ID": "RCA0217NVS",
      "Year/Grade": 2,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834861",
    },
    {
      "First Name": "Impano",
      "Last Name": "Alliance",
      "Code/ID": "RCA0218NKA",
      "Year/Grade": 2,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834862",
    },
    {
      "First Name": "Ineza",
      "Last Name": "Naillah",
      "Code/ID": "RCA0219SJH",
      "Year/Grade": 2,
      Class: "C",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834863",
    },
    {
      "First Name": "Ineza",
      "Last Name": "Ange Michaella",
      "Code/ID": "RCA0220KYT",
      "Year/Grade": 2,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834864",
    },
    {
      "First Name": "Ineza Jost",
      "Last Name": "Chance",
      "Code/ID": "RCA0221DMU",
      "Year/Grade": 2,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834865",
    },
    {
      "First Name": "Iradukunda",
      "Last Name": "Clarisse",
      "Code/ID": "RCA0222SIT",
      "Year/Grade": 2,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834866",
    },
    {
      "First Name": "Iradukunda",
      "Last Name": "Verite",
      "Code/ID": "RCA0223UTZ",
      "Year/Grade": 2,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834867",
    },
    {
      "First Name": "Irategeka Neza",
      "Last Name": "Bruce",
      "Code/ID": "RCA0224AXZ",
      "Year/Grade": 2,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834868",
    },
    {
      "First Name": "Ishimwe",
      "Last Name": "Teta Lena",
      "Code/ID": "RCA0225DYY",
      "Year/Grade": 2,
      Class: "C",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834869",
    },
    {
      "First Name": "Isite",
      "Last Name": "Yves",
      "Code/ID": "RCA0226LDV",
      "Year/Grade": 2,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834870",
    },
    {
      "First Name": "Itetero",
      "Last Name": "Ariane",
      "Code/ID": "RCA0227XIJ",
      "Year/Grade": 2,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834871",
    },
    {
      "First Name": "Kalisa",
      "Last Name": "Belyse",
      "Code/ID": "RCA0228MWW",
      "Year/Grade": 2,
      Class: "C",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834872",
    },
    {
      "First Name": "Kamara",
      "Last Name": "Fidele",
      "Code/ID": "RCA0229WBR",
      "Year/Grade": 2,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834873",
    },
    {
      "First Name": "Karera",
      "Last Name": "Marvin",
      "Code/ID": "RCA0230BLW",
      "Year/Grade": 2,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834874",
    },
    {
      "First Name": "Kayigire Ngabire",
      "Last Name": "Kethia",
      "Code/ID": "RCA0231RBI",
      "Year/Grade": 2,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834875",
    },
    {
      "First Name": "Kayitare",
      "Last Name": "Audax",
      "Code/ID": "RCA0232LUJ",
      "Year/Grade": 2,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834876",
    },
    {
      "First Name": "Kunda",
      "Last Name": "Mugisha sarah",
      "Code/ID": "RCA0233EAM",
      "Year/Grade": 2,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834877",
    },
    {
      "First Name": "Mfitumukiza",
      "Last Name": "Peter",
      "Code/ID": "RCA0234MGD",
      "Year/Grade": 2,
      Class: "C",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834878",
    },
    {
      "First Name": "Mizero",
      "Last Name": "Eloi",
      "Code/ID": "RCA0235YGN",
      "Year/Grade": 2,
      Class: "C",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834879",
    },
    {
      "First Name": "Mpano",
      "Last Name": "Christian",
      "Code/ID": "RCA0236VGD",
      "Year/Grade": 2,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834880",
    },
    {
      "First Name": "Mudahemuka",
      "Last Name": "Manzi",
      "Code/ID": "RCA0237MBR",
      "Year/Grade": 2,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834881",
    },
    {
      "First Name": "Muhire",
      "Last Name": "Patrick",
      "Code/ID": "RCA0238CWM",
      "Year/Grade": 2,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834882",
    },
    {
      "First Name": "MUHOZA",
      "Last Name": "Olivier Ivan",
      "Code/ID": "RCA0239HRZ",
      "Year/Grade": 2,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834883",
    },
    {
      "First Name": "Munganyinka",
      "Last Name": "Shakira",
      "Code/ID": "RCA0240TKU",
      "Year/Grade": 2,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834884",
    },
    {
      "First Name": "Mutegetsi",
      "Last Name": "Prince",
      "Code/ID": "RCA0241RBM",
      "Year/Grade": 2,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834885",
    },
    {
      "First Name": "Mwizera",
      "Last Name": "Amen Gisele",
      "Code/ID": "RCA0242YUV",
      "Year/Grade": 2,
      Class: "C",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834886",
    },
    {
      "First Name": "Niyigena",
      "Last Name": "Tresor",
      "Code/ID": "RCA0243HGY",
      "Year/Grade": 2,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834887",
    },
    {
      "First Name": "Niyigena",
      "Last Name": "Yves",
      "Code/ID": "RCA0244DYI",
      "Year/Grade": 2,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834888",
    },
    {
      "First Name": "Nkubito",
      "Last Name": "Pacis",
      "Code/ID": "RCA0245PVK",
      "Year/Grade": 2,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834889",
    },
    {
      "First Name": "Nshuti",
      "Last Name": "Jabes",
      "Code/ID": "RCA0246HGK",
      "Year/Grade": 2,
      Class: "C",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834890",
    },
    {
      "First Name": "Ntagungira",
      "Last Name": "Ali Rashid",
      "Code/ID": "RCA0247BJW",
      "Year/Grade": 2,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834891",
    },
    {
      "First Name": "Rugero",
      "Last Name": "Beulla",
      "Code/ID": "RCA0248GPB",
      "Year/Grade": 2,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834892",
    },
    {
      "First Name": "Rutayisire",
      "Last Name": "Ange Belard",
      "Code/ID": "RCA0249PII",
      "Year/Grade": 2,
      Class: "C",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834893",
    },
    {
      "First Name": "Rwagapfizi",
      "Last Name": "Igor Roggy",
      "Code/ID": "RCA0250HTR",
      "Year/Grade": 2,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834894",
    },
    {
      "First Name": "SETH",
      "Last Name": "ABIJURU",
      "Code/ID": "RCA0251SKX",
      "Year/Grade": 2,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834895",
    },
    {
      "First Name": "Shumbusho",
      "Last Name": "David",
      "Code/ID": "RCA0252BUT",
      "Year/Grade": 2,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834896",
    },
    {
      "First Name": "Ishimwe",
      "Last Name": "Shumbusho Anglebert",
      "Code/ID": "RCA0253VCB",
      "Year/Grade": 2,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834897",
    },
    {
      "First Name": "Singizwa",
      "Last Name": "Nick",
      "Code/ID": "RCA0254IRL",
      "Year/Grade": 2,
      Class: "C",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834898",
    },
    {
      "First Name": "Teta",
      "Last Name": "Butera Nelly",
      "Code/ID": "RCA0255LYI",
      "Year/Grade": 2,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834899",
    },
    {
      "First Name": "Turinumugisha",
      "Last Name": "Souvenir",
      "Code/ID": "RCA0256JIW",
      "Year/Grade": 2,
      Class: "C",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834900",
    },
    {
      "First Name": "Umuhoza",
      "Last Name": "Esther",
      "Code/ID": "RCA0257AIZ",
      "Year/Grade": 2,
      Class: "C",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834901",
    },
    {
      "First Name": "Umutoniwabo",
      "Last Name": "Hasbiyallah",
      "Code/ID": "RCA0258DDA",
      "Year/Grade": 2,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834902",
    },
    {
      "First Name": "Uwamungu",
      "Last Name": "Gasaro Marie Leila",
      "Code/ID": "RCA0259TEE",
      "Year/Grade": 2,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834903",
    },
    {
      "First Name": "Uwenayo",
      "Last Name": "Alain Pacifique",
      "Code/ID": "RCA0260EZE",
      "Year/Grade": 2,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834904",
    },
  ],
  year_3: [
    {
      "First Name": "Abizera",
      "Last Name": "Oreste",
      "Code/ID": "RCA0101SHI",
      "Year/Grade": 3,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834845",
    },
    {
      "First Name": "Cyebukayire",
      "Last Name": "Peace",
      "Code/ID": "RCA0103GAK",
      "Year/Grade": 3,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834846",
    },
    {
      "First Name": "Cyusa",
      "Last Name": "Munezero Keny",
      "Code/ID": "RCA0104TGJ",
      "Year/Grade": 3,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834847",
    },
    {
      "First Name": "Dukundane",
      "Last Name": "Daniel",
      "Code/ID": "RCA0105CNX",
      "Year/Grade": 3,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834848",
    },
    {
      "First Name": "Dusengimana",
      "Last Name": "Felix",
      "Code/ID": "RCA0106HQT",
      "Year/Grade": 3,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834849",
    },
    {
      "First Name": "Dushimimana",
      "Last Name": "Samuel",
      "Code/ID": "RCA0107TNP",
      "Year/Grade": 3,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834850",
    },
    {
      "First Name": "Gahamanyi",
      "Last Name": "Yvette",
      "Code/ID": "RCA0108XYB",
      "Year/Grade": 3,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834851",
    },
    {
      "First Name": "Gisa Kaze",
      "Last Name": "Fredson",
      "Code/ID": "RCA0109QNU",
      "Year/Grade": 3,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834852",
    },
    {
      "First Name": "Hagenimana",
      "Last Name": "Yassin",
      "Code/ID": "RCA0110JFX",
      "Year/Grade": 3,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834853",
    },
    {
      "First Name": "Harerimana",
      "Last Name": "Egide",
      "Code/ID": "RCA0111MYG",
      "Year/Grade": 3,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834854",
    },
    {
      "First Name": "Hirwa",
      "Last Name": "Blessing",
      "Code/ID": "RCA0112WBA",
      "Year/Grade": 3,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834855",
    },
    {
      "First Name": "Hirwa Marie -Faustine",
      "Last Name": "Chanelle",
      "Code/ID": "RCA0113MHB",
      "Year/Grade": 3,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834856",
    },
    {
      "First Name": "Igiraneza",
      "Last Name": "Honorine",
      "Code/ID": "RCA0114XBI",
      "Year/Grade": 3,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834857",
    },
    {
      "First Name": "Ikirezi",
      "Last Name": "Ndayambaje Ange Divine",
      "Code/ID": "RCA0115IEW",
      "Year/Grade": 3,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834858",
    },
    {
      "First Name": "Ineza",
      "Last Name": "Aimee Annabelle",
      "Code/ID": "RCA0116GMM",
      "Year/Grade": 3,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834859",
    },
    {
      "First Name": "Ineza",
      "Last Name": "Bella Melissa",
      "Code/ID": "RCA0117AFB",
      "Year/Grade": 3,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834860",
    },
    {
      "First Name": "Inshuti",
      "Last Name": "Joyeuse Souvede",
      "Code/ID": "RCA0118QDX",
      "Year/Grade": 3,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834861",
    },
    {
      "First Name": "Iradukunda",
      "Last Name": "Best Verie",
      "Code/ID": "RCA0119RTL",
      "Year/Grade": 3,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834862",
    },
    {
      "First Name": "Iradukunda",
      "Last Name": "Landrada",
      "Code/ID": "RCA0120KCR",
      "Year/Grade": 3,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834863",
    },
    {
      "First Name": "Iradukunda",
      "Last Name": "Tamara Merlyne",
      "Code/ID": "RCA0121JQP",
      "Year/Grade": 3,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834864",
    },
    {
      "First Name": "Irakiza",
      "Last Name": "Divin",
      "Code/ID": "RCA0122QLR",
      "Year/Grade": 3,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834865",
    },
    {
      "First Name": "Irakoze",
      "Last Name": "Marie Reine Hortance",
      "Code/ID": "RCA0123RZX",
      "Year/Grade": 3,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834866",
    },
    {
      "First Name": "Irakoze Mukezwa",
      "Last Name": "Loraine",
      "Code/ID": "RCA0124TXA",
      "Year/Grade": 3,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834867",
    },
    {
      "First Name": "Irumva",
      "Last Name": "Habumugisha Anselme",
      "Code/ID": "RCA0125BGE",
      "Year/Grade": 3,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834868",
    },
    {
      "First Name": "Ishimwe",
      "Last Name": "Gervais",
      "Code/ID": "RCA0126XMR",
      "Year/Grade": 3,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834869",
    },
    {
      "First Name": "Ishimwe",
      "Last Name": "Marie Pauline",
      "Code/ID": "RCA0127LMW",
      "Year/Grade": 3,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834870",
    },
    {
      "First Name": "Izabayo",
      "Last Name": "Cedric",
      "Code/ID": "RCA0128MDA",
      "Year/Grade": 3,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834871",
    },
    {
      "First Name": "Izere Uwonkunda",
      "Last Name": "Marie Claire Kerie",
      "Code/ID": "RCA0129LUT",
      "Year/Grade": 3,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834872",
    },
    {
      "First Name": "Kobusinge",
      "Last Name": "Shallon",
      "Code/ID": "RCA0130YFW",
      "Year/Grade": 3,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834873",
    },
    {
      "First Name": "Kwizera",
      "Last Name": "Emmanuel",
      "Code/ID": "RCA0131PPM",
      "Year/Grade": 3,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834874",
    },
    {
      "First Name": "Mahoro",
      "Last Name": "Phinah",
      "Code/ID": "RCA0132DFZ",
      "Year/Grade": 3,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834875",
    },
    {
      "First Name": "Makuza",
      "Last Name": "Mugabo Verite",
      "Code/ID": "RCA0133UYX",
      "Year/Grade": 3,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834876",
    },
    {
      "First Name": "Manzi",
      "Last Name": "Gustave",
      "Code/ID": "RCA0134TRW",
      "Year/Grade": 3,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834877",
    },
    {
      "First Name": "Manzi Twahirwa",
      "Last Name": "Mike",
      "Code/ID": "RCA0135USA",
      "Year/Grade": 3,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834878",
    },
    {
      "First Name": "Mfuranziza Sekata",
      "Last Name": "Aimelyse Moss",
      "Code/ID": "RCA0136XRQ",
      "Year/Grade": 3,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834879",
    },
    {
      "First Name": "Mugisha",
      "Last Name": "Edine Noella",
      "Code/ID": "RCA0137QCD",
      "Year/Grade": 3,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834880",
    },
    {
      "First Name": "Mugisha",
      "Last Name": "Isaac",
      "Code/ID": "RCA0138MQG",
      "Year/Grade": 3,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834881",
    },
    {
      "First Name": "Muhodari",
      "Last Name": "Sage",
      "Code/ID": "RCA0139MBA",
      "Year/Grade": 3,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834882",
    },
    {
      "First Name": "Mukundwa",
      "Last Name": "Ange Nicole",
      "Code/ID": "RCA0140GZG",
      "Year/Grade": 3,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834883",
    },
    {
      "First Name": "Munezero",
      "Last Name": "Didier",
      "Code/ID": "RCA0141DNV",
      "Year/Grade": 3,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834884",
    },
    {
      "First Name": "Murenzi",
      "Last Name": "Confiance Tracy",
      "Code/ID": "RCA0142QRB",
      "Year/Grade": 3,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834885",
    },
    {
      "First Name": "Mutoni Uwingeneye",
      "Last Name": "Denyse",
      "Code/ID": "RCA0143PLZ",
      "Year/Grade": 3,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834886",
    },
    {
      "First Name": "Nimuhire",
      "Last Name": "Ange Constance",
      "Code/ID": "RCA0144NFQ",
      "Year/Grade": 3,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834887",
    },
    {
      "First Name": "Niyogitare",
      "Last Name": "Patrick",
      "Code/ID": "RCA0145KXH",
      "Year/Grade": 3,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834888",
    },
    {
      "First Name": "Niyonzima",
      "Last Name": "Stecie",
      "Code/ID": "RCA0146NYZ",
      "Year/Grade": 3,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834889",
    },
    {
      "First Name": "Nsengiyumva",
      "Last Name": "Gershom",
      "Code/ID": "RCA0147DMC",
      "Year/Grade": 3,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834890",
    },
    {
      "First Name": "Nshimiyandinze",
      "Last Name": "Fiston",
      "Code/ID": "RCA0148GZT",
      "Year/Grade": 3,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834891",
    },
    {
      "First Name": "Nshimiye",
      "Last Name": "Emmy",
      "Code/ID": "RCA0149NMU",
      "Year/Grade": 3,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834892",
    },
    {
      "First Name": "Ntakirutimana",
      "Last Name": "Pretty Diane",
      "Code/ID": "RCA0150PTT",
      "Year/Grade": 3,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834893",
    },
    {
      "First Name": "Ntezirizaza",
      "Last Name": "Erneste",
      "Code/ID": "RCA0151VWH",
      "Year/Grade": 3,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834894",
    },
    {
      "First Name": "Ntwari",
      "Last Name": "Clarance Liberiste",
      "Code/ID": "RCA0152RMZ",
      "Year/Grade": 3,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834895",
    },
    {
      "First Name": "Ntwali",
      "Last Name": "Egide",
      "Code/ID": "RCA0153SBK",
      "Year/Grade": 3,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834896",
    },
    {
      "First Name": "Sauve",
      "Last Name": "Jean Luc",
      "Code/ID": "RCA0154RQQ",
      "Year/Grade": 3,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834897",
    },
    {
      "First Name": "Tuyishime",
      "Last Name": "Jean d-Amour",
      "Code/ID": "RCA0155HAP",
      "Year/Grade": 3,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834898",
    },
    {
      "First Name": "Twizeyimana",
      "Last Name": "Elissa",
      "Code/ID": "RCA0156PNM",
      "Year/Grade": 3,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834899",
    },
    {
      "First Name": "Twizeyimana",
      "Last Name": "Jacques",
      "Code/ID": "RCA0157PRZ",
      "Year/Grade": 3,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834900",
    },
    {
      "First Name": "Umuhire",
      "Last Name": "Kellia",
      "Code/ID": "RCA0158RXZ",
      "Year/Grade": 3,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834901",
    },
    {
      "First Name": "Uwababyeyi",
      "Last Name": "Anne Bethiane",
      "Code/ID": "RCA0159JML",
      "Year/Grade": 3,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834902",
    },
  ],
  year_1: [
    {
      "First Name": "AMIZERO",
      "Last Name": "IRIZA PEACE MARY",
      "Code/ID": "RCA0301BNL",
      "Year/Grade": 1,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834845",
    },
    {
      "First Name": "AMIZERO",
      "Last Name": "NSABIMANA Peace Thierry Tresor",
      "Code/ID": "RCA0302RYZ",
      "Year/Grade": 1,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834846",
    },
    {
      "First Name": "BIGWI",
      "Last Name": "SHYAKA Valentin",
      "Code/ID": "RCA0303NAY",
      "Year/Grade": 1,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834847",
    },
    {
      "First Name": "BIRAMAHIRE",
      "Last Name": "Dan Bellamy",
      "Code/ID": "RCA0304RLE",
      "Year/Grade": 1,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834848",
    },
    {
      "First Name": "BISIZI",
      "Last Name": "MUHIRE Ighor",
      "Code/ID": "RCA0305GUU",
      "Year/Grade": 1,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834849",
    },
    {
      "First Name": "BUGINGO",
      "Last Name": "Elua",
      "Code/ID": "RCA0306WBE",
      "Year/Grade": 1,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834850",
    },
    {
      "First Name": "DUKUNDANE",
      "Last Name": "FURAHA Yves Derick",
      "Code/ID": "RCA0307VLB",
      "Year/Grade": 1,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834851",
    },
    {
      "First Name": "DUSHIME",
      "Last Name": "VALENTIN",
      "Code/ID": "RCA0308MYH",
      "Year/Grade": 1,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834852",
    },
    {
      "First Name": "DUSHIMIYIMANA",
      "Last Name": "Jazzy Bruno",
      "Code/ID": "RCA0309JBM",
      "Year/Grade": 1,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834853",
    },
    {
      "First Name": "GAKUBA",
      "Last Name": "Edmond",
      "Code/ID": "RCA0310LUB",
      "Year/Grade": 1,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834854",
    },
    {
      "First Name": "GISINGIZO",
      "Last Name": "GLORIA",
      "Code/ID": "RCA0311GLU",
      "Year/Grade": 1,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834855",
    },
    {
      "First Name": "HIRWA",
      "Last Name": "GACURABWENGE Vanessa",
      "Code/ID": "RCA0312NJU",
      "Year/Grade": 1,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834856",
    },
    {
      "First Name": "IMANISHIMWE",
      "Last Name": "Emmanuel",
      "Code/ID": "RCA0313GNE",
      "Year/Grade": 1,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834857",
    },
    {
      "First Name": "IMFURA",
      "Last Name": "MURINDA Huguette",
      "Code/ID": "RCA0314PNZ",
      "Year/Grade": 1,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834858",
    },
    {
      "First Name": "INEZA",
      "Last Name": "Axelle",
      "Code/ID": "RCA0315BMN",
      "Year/Grade": 1,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834859",
    },
    {
      "First Name": "INGABIRE",
      "Last Name": "Divine",
      "Code/ID": "RCA0316BVL",
      "Year/Grade": 1,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834860",
    },
    {
      "First Name": "IRADUKUNDA",
      "Last Name": "Mustafa",
      "Code/ID": "RCA0317ZVM",
      "Year/Grade": 1,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834861",
    },
    {
      "First Name": "IRAKARAMA",
      "Last Name": "Laurent",
      "Code/ID": "RCA0318ERM",
      "Year/Grade": 1,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834862",
    },
    {
      "First Name": "IRATUZI",
      "Last Name": "JEHOVA TSIKENI",
      "Code/ID": "RCA0319JML",
      "Year/Grade": 1,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834863",
    },
    {
      "First Name": "ISHIMWE",
      "Last Name": "SUGIRA Yvan",
      "Code/ID": "RCA0320RUL",
      "Year/Grade": 1,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834864",
    },
    {
      "First Name": "ISHIMWE",
      "Last Name": "KEVINE",
      "Code/ID": "RCA0321EMV",
      "Year/Grade": 1,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834865",
    },
    {
      "First Name": "ISHIMWE",
      "Last Name": "VAINQUEUR",
      "Code/ID": "RCA0322RJU",
      "Year/Grade": 1,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834866",
    },
    {
      "First Name": "ISHIMWE NDUNGUTSE",
      "Last Name": "CHARLES",
      "Code/ID": "RCA0323YGU",
      "Year/Grade": 1,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834867",
    },
    {
      "First Name": "ISIMBI",
      "Last Name": "KEZA LYSA",
      "Code/ID": "RCA0324HWP",
      "Year/Grade": 1,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834868",
    },
    {
      "First Name": "KABALISA",
      "Last Name": "Mugisha Melissa",
      "Code/ID": "RCA0325JGW",
      "Year/Grade": 1,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834869",
    },
    {
      "First Name": "KABANDA",
      "Last Name": "MANZI Cedrick",
      "Code/ID": "RCA0326WPU",
      "Year/Grade": 1,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834870",
    },
    {
      "First Name": "KALISA",
      "Last Name": "INEZA Giovanni",
      "Code/ID": "RCA0327GNY",
      "Year/Grade": 1,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834871",
    },
    {
      "First Name": "KARABO",
      "Last Name": "Nadege Diamant",
      "Code/ID": "RCA0328EUB",
      "Year/Grade": 1,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834872",
    },
    {
      "First Name": "KARIGIRWA",
      "Last Name": "Sonia Olga",
      "Code/ID": "RCA0329EMJ",
      "Year/Grade": 1,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834873",
    },
    {
      "First Name": "MAJURA",
      "Last Name": "Anthony Gaudence",
      "Code/ID": "RCA0330ZGV",
      "Year/Grade": 1,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834874",
    },
    {
      "First Name": "MANISHIMWE",
      "Last Name": "YVETTE",
      "Code/ID": "RCA0331UGY",
      "Year/Grade": 1,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834875",
    },
    {
      "First Name": "MANZI",
      "Last Name": "Israel",
      "Code/ID": "RCA0332WHA",
      "Year/Grade": 1,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834876",
    },
    {
      "First Name": "MUGISHA",
      "Last Name": "PUCEAU PRECIEUX",
      "Code/ID": "RCA0333RLN",
      "Year/Grade": 1,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834877",
    },
    {
      "First Name": "MUGISHA",
      "Last Name": "DORCUS",
      "Code/ID": "RCA0334EBU",
      "Year/Grade": 1,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834878",
    },
    {
      "First Name": "MURANGWA",
      "Last Name": "PACIFIQUE",
      "Code/ID": "RCA0335ARW",
      "Year/Grade": 1,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834879",
    },
    {
      "First Name": "MUTESA",
      "Last Name": "CEDRIC",
      "Code/ID": "RCA0336JBN",
      "Year/Grade": 1,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834880",
    },
    {
      "First Name": "MUTUYIMANA",
      "Last Name": "JOYEUSE RITA",
      "Code/ID": "RCA0337VBP",
      "Year/Grade": 1,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834881",
    },
    {
      "First Name": "MWENEDATA",
      "Last Name": "Apotre",
      "Code/ID": "RCA0338BEZ",
      "Year/Grade": 1,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834882",
    },
    {
      "First Name": "NDAYAMBAJE",
      "Last Name": "Patrick",
      "Code/ID": "RCA0339WNM",
      "Year/Grade": 1,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834883",
    },
    {
      "First Name": "NDAYISHIMIYE",
      "Last Name": "GILBERT",
      "Code/ID": "RCA0340WLW",
      "Year/Grade": 1,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834884",
    },
    {
      "First Name": "NDIZIHIWE",
      "Last Name": "REGIS",
      "Code/ID": "RCA0341UUJ",
      "Year/Grade": 1,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834885",
    },
    {
      "First Name": "Ngabo",
      "Last Name": "Iris",
      "Code/ID": "RCA0342LEZ",
      "Year/Grade": 1,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834886",
    },
    {
      "First Name": "NIBAKURE",
      "Last Name": "Josephine",
      "Code/ID": "RCA0343RWW",
      "Year/Grade": 1,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834887",
    },
    {
      "First Name": "NIYIDUHUMUGISHA",
      "Last Name": "EDEN",
      "Code/ID": "RCA0344AUP",
      "Year/Grade": 1,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834888",
    },
    {
      "First Name": "NIYOMUNGELI",
      "Last Name": "ALINE",
      "Code/ID": "RCA0345RMR",
      "Year/Grade": 1,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834889",
    },
    {
      "First Name": "NIYONSENGA",
      "Last Name": "VALENS",
      "Code/ID": "RCA0346RAP",
      "Year/Grade": 1,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834890",
    },
    {
      "First Name": "NKUBITOYIMANZI",
      "Last Name": "RUTH",
      "Code/ID": "RCA0347EBP",
      "Year/Grade": 1,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834891",
    },
    {
      "First Name": "Nyishimente",
      "Last Name": "Lois",
      "Code/ID": "RCA0348MUU",
      "Year/Grade": 1,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834892",
    },
    {
      "First Name": "NZAMBAZAMARIYA",
      "Last Name": "ROSINE",
      "Code/ID": "RCA0349JVW",
      "Year/Grade": 1,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834893",
    },
    {
      "First Name": "RUKUNDO",
      "Last Name": "HONORE",
      "Code/ID": "RCA0350JHJ",
      "Year/Grade": 1,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834894",
    },
    {
      "First Name": "RUTAGENGWA",
      "Last Name": "ASANTE BRUCE",
      "Code/ID": "RCA0351YHG",
      "Year/Grade": 1,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834895",
    },
    {
      "First Name": "UJENEZA",
      "Last Name": "DIVINE",
      "Code/ID": "RCA0352ERR",
      "Year/Grade": 1,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834896",
    },
    {
      "First Name": "UMUGWANEZA",
      "Last Name": "Alice",
      "Code/ID": "RCA0353ANU",
      "Year/Grade": 1,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834897",
    },
    {
      "First Name": "UMUGWANEZA",
      "Last Name": "ANAISE",
      "Code/ID": "RCA0354JNL",
      "Year/Grade": 1,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834898",
    },
    {
      "First Name": "UMUTONI",
      "Last Name": "MIREILLE",
      "Code/ID": "RCA0355HGN",
      "Year/Grade": 1,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834899",
    },
    {
      "First Name": "UMWALI",
      "Last Name": "Cynthia",
      "Code/ID": "RCA0356RHB",
      "Year/Grade": 1,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834900",
    },
    {
      "First Name": "UNYUZIMFURA",
      "Last Name": "ISHIMWE JOY KEVIN",
      "Code/ID": "RCA0357YAB",
      "Year/Grade": 1,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834901",
    },
    {
      "First Name": "USHIMIRWA",
      "Last Name": "INGABIRE BENITHA",
      "Code/ID": "RCA0358MYV",
      "Year/Grade": 1,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834902",
    },
    {
      "First Name": "UWASE",
      "Last Name": "Lina",
      "Code/ID": "RCA0359AHW",
      "Year/Grade": 1,
      Class: "A",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834903",
    },
    {
      "First Name": "UWIRINGIYIMANA",
      "Last Name": "MARTHE",
      "Code/ID": "RCA0360MAW",
      "Year/Grade": 1,
      Class: "B",
      "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
      "Parent Tel(s)": "0782307144, 0788834904",
    },
  ],
};

export const AllStudentsDisplay: any = [
  {
    "First Name": "IGIRIMPUHWE",
    "Last Name": "Aime",
    "Code/ID": "RCA0201NSZ",
    "Year/Grade": 2,
    Class: "C",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834845",
  },
  {
    "First Name": "Biziyaremye",
    "Last Name": "Henriette",
    "Code/ID": "RCA0202JIZ",
    "Year/Grade": 2,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834846",
  },
  {
    "First Name": "Burigo",
    "Last Name": "Aldo Jabes",
    "Code/ID": "RCA0203NMZ",
    "Year/Grade": 2,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834847",
  },
  {
    "First Name": "Bwiza",
    "Last Name": "Nina",
    "Code/ID": "RCA0204ZUR",
    "Year/Grade": 2,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834848",
  },
  {
    "First Name": "Byiringiro",
    "Last Name": "Saad",
    "Code/ID": "RCA0205HDV",
    "Year/Grade": 2,
    Class: "C",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834849",
  },
  {
    "First Name": "DABAGIRE",
    "Last Name": "Valens",
    "Code/ID": "RCA0206AKB",
    "Year/Grade": 2,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834850",
  },
  {
    "First Name": "Dufitumukiza",
    "Last Name": "Emmanuel",
    "Code/ID": "RCA0207RVY",
    "Year/Grade": 2,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834851",
  },
  {
    "First Name": "Dukunde Irakoze",
    "Last Name": "Acele Happy",
    "Code/ID": "RCA0208ZAK",
    "Year/Grade": 2,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834852",
  },
  {
    "First Name": "Dushime",
    "Last Name": "Grace Fidele",
    "Code/ID": "RCA0209ZNK",
    "Year/Grade": 2,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834853",
  },
  {
    "First Name": "Dushime",
    "Last Name": "Bill Benon",
    "Code/ID": "RCA0210GNU",
    "Year/Grade": 2,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834854",
  },
  {
    "First Name": "Dushimimana",
    "Last Name": "Sandrine",
    "Code/ID": "RCA0211ZXU",
    "Year/Grade": 2,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834855",
  },
  {
    "First Name": "Gashugi Muhimpundu",
    "Last Name": "Aderline",
    "Code/ID": "RCA0212RKE",
    "Year/Grade": 2,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834856",
  },
  {
    "First Name": "Gikundiro Larissa",
    "Last Name": "Teta",
    "Code/ID": "RCA0213KKA",
    "Year/Grade": 2,
    Class: "C",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834857",
  },
  {
    "First Name": "Girishya",
    "Last Name": "Fiat Bruno",
    "Code/ID": "RCA0214KTL",
    "Year/Grade": 2,
    Class: "C",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834858",
  },
  {
    "First Name": "Igihozo Nyituriki",
    "Last Name": "Marie Colombe",
    "Code/ID": "RCA0215HDC",
    "Year/Grade": 2,
    Class: "C",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834859",
  },
  {
    "First Name": "Ihozo",
    "Last Name": "Marie Honnette",
    "Code/ID": "RCA0216EBG",
    "Year/Grade": 2,
    Class: "C",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834860",
  },
  {
    "First Name": "Imanzi",
    "Last Name": "Yannick Kenny",
    "Code/ID": "RCA0217NVS",
    "Year/Grade": 2,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834861",
  },
  {
    "First Name": "Impano",
    "Last Name": "Alliance",
    "Code/ID": "RCA0218NKA",
    "Year/Grade": 2,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834862",
  },
  {
    "First Name": "Ineza",
    "Last Name": "Naillah",
    "Code/ID": "RCA0219SJH",
    "Year/Grade": 2,
    Class: "C",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834863",
  },
  {
    "First Name": "Ineza",
    "Last Name": "Ange Michaella",
    "Code/ID": "RCA0220KYT",
    "Year/Grade": 2,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834864",
  },
  {
    "First Name": "Ineza Jost",
    "Last Name": "Chance",
    "Code/ID": "RCA0221DMU",
    "Year/Grade": 2,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834865",
  },
  {
    "First Name": "Iradukunda",
    "Last Name": "Clarisse",
    "Code/ID": "RCA0222SIT",
    "Year/Grade": 2,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834866",
  },
  {
    "First Name": "Iradukunda",
    "Last Name": "Verite",
    "Code/ID": "RCA0223UTZ",
    "Year/Grade": 2,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834867",
  },
  {
    "First Name": "Irategeka Neza",
    "Last Name": "Bruce",
    "Code/ID": "RCA0224AXZ",
    "Year/Grade": 2,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834868",
  },
  {
    "First Name": "Ishimwe",
    "Last Name": "Teta Lena",
    "Code/ID": "RCA0225DYY",
    "Year/Grade": 2,
    Class: "C",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834869",
  },
  {
    "First Name": "Isite",
    "Last Name": "Yves",
    "Code/ID": "RCA0226LDV",
    "Year/Grade": 2,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834870",
  },
  {
    "First Name": "Itetero",
    "Last Name": "Ariane",
    "Code/ID": "RCA0227XIJ",
    "Year/Grade": 2,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834871",
  },
  {
    "First Name": "Kalisa",
    "Last Name": "Belyse",
    "Code/ID": "RCA0228MWW",
    "Year/Grade": 2,
    Class: "C",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834872",
  },
  {
    "First Name": "Kamara",
    "Last Name": "Fidele",
    "Code/ID": "RCA0229WBR",
    "Year/Grade": 2,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834873",
  },
  {
    "First Name": "Karera",
    "Last Name": "Marvin",
    "Code/ID": "RCA0230BLW",
    "Year/Grade": 2,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834874",
  },
  {
    "First Name": "Kayigire Ngabire",
    "Last Name": "Kethia",
    "Code/ID": "RCA0231RBI",
    "Year/Grade": 2,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834875",
  },
  {
    "First Name": "Kayitare",
    "Last Name": "Audax",
    "Code/ID": "RCA0232LUJ",
    "Year/Grade": 2,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834876",
  },
  {
    "First Name": "Kunda",
    "Last Name": "Mugisha sarah",
    "Code/ID": "RCA0233EAM",
    "Year/Grade": 2,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834877",
  },
  {
    "First Name": "Mfitumukiza",
    "Last Name": "Peter",
    "Code/ID": "RCA0234MGD",
    "Year/Grade": 2,
    Class: "C",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834878",
  },
  {
    "First Name": "Mizero",
    "Last Name": "Eloi",
    "Code/ID": "RCA0235YGN",
    "Year/Grade": 2,
    Class: "C",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834879",
  },
  {
    "First Name": "Mpano",
    "Last Name": "Christian",
    "Code/ID": "RCA0236VGD",
    "Year/Grade": 2,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834880",
  },
  {
    "First Name": "Mudahemuka",
    "Last Name": "Manzi",
    "Code/ID": "RCA0237MBR",
    "Year/Grade": 2,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834881",
  },
  {
    "First Name": "Muhire",
    "Last Name": "Patrick",
    "Code/ID": "RCA0238CWM",
    "Year/Grade": 2,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834882",
  },
  {
    "First Name": "MUHOZA",
    "Last Name": "Olivier Ivan",
    "Code/ID": "RCA0239HRZ",
    "Year/Grade": 2,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834883",
  },
  {
    "First Name": "Munganyinka",
    "Last Name": "Shakira",
    "Code/ID": "RCA0240TKU",
    "Year/Grade": 2,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834884",
  },
  {
    "First Name": "Mutegetsi",
    "Last Name": "Prince",
    "Code/ID": "RCA0241RBM",
    "Year/Grade": 2,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834885",
  },
  {
    "First Name": "Mwizera",
    "Last Name": "Amen Gisele",
    "Code/ID": "RCA0242YUV",
    "Year/Grade": 2,
    Class: "C",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834886",
  },
  {
    "First Name": "Niyigena",
    "Last Name": "Tresor",
    "Code/ID": "RCA0243HGY",
    "Year/Grade": 2,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834887",
  },
  {
    "First Name": "Niyigena",
    "Last Name": "Yves",
    "Code/ID": "RCA0244DYI",
    "Year/Grade": 2,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834888",
  },
  {
    "First Name": "Nkubito",
    "Last Name": "Pacis",
    "Code/ID": "RCA0245PVK",
    "Year/Grade": 2,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834889",
  },
  {
    "First Name": "Nshuti",
    "Last Name": "Jabes",
    "Code/ID": "RCA0246HGK",
    "Year/Grade": 2,
    Class: "C",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834890",
  },
  {
    "First Name": "Ntagungira",
    "Last Name": "Ali Rashid",
    "Code/ID": "RCA0247BJW",
    "Year/Grade": 2,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834891",
  },
  {
    "First Name": "Rugero",
    "Last Name": "Beulla",
    "Code/ID": "RCA0248GPB",
    "Year/Grade": 2,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834892",
  },
  {
    "First Name": "Rutayisire",
    "Last Name": "Ange Belard",
    "Code/ID": "RCA0249PII",
    "Year/Grade": 2,
    Class: "C",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834893",
  },
  {
    "First Name": "Rwagapfizi",
    "Last Name": "Igor Roggy",
    "Code/ID": "RCA0250HTR",
    "Year/Grade": 2,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834894",
  },
  {
    "First Name": "SETH",
    "Last Name": "ABIJURU",
    "Code/ID": "RCA0251SKX",
    "Year/Grade": 2,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834895",
  },
  {
    "First Name": "Shumbusho",
    "Last Name": "David",
    "Code/ID": "RCA0252BUT",
    "Year/Grade": 2,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834896",
  },
  {
    "First Name": "Ishimwe",
    "Last Name": "Shumbusho Anglebert",
    "Code/ID": "RCA0253VCB",
    "Year/Grade": 2,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834897",
  },
  {
    "First Name": "Singizwa",
    "Last Name": "Nick",
    "Code/ID": "RCA0254IRL",
    "Year/Grade": 2,
    Class: "C",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834898",
  },
  {
    "First Name": "Teta",
    "Last Name": "Butera Nelly",
    "Code/ID": "RCA0255LYI",
    "Year/Grade": 2,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834899",
  },
  {
    "First Name": "Turinumugisha",
    "Last Name": "Souvenir",
    "Code/ID": "RCA0256JIW",
    "Year/Grade": 2,
    Class: "C",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834900",
  },
  {
    "First Name": "Umuhoza",
    "Last Name": "Esther",
    "Code/ID": "RCA0257AIZ",
    "Year/Grade": 2,
    Class: "C",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834901",
  },
  {
    "First Name": "Umutoniwabo",
    "Last Name": "Hasbiyallah",
    "Code/ID": "RCA0258DDA",
    "Year/Grade": 2,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834902",
  },
  {
    "First Name": "Uwamungu",
    "Last Name": "Gasaro Marie Leila",
    "Code/ID": "RCA0259TEE",
    "Year/Grade": 2,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834903",
  },
  {
    "First Name": "Uwenayo",
    "Last Name": "Alain Pacifique",
    "Code/ID": "RCA0260EZE",
    "Year/Grade": 2,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834904",
  },
  {
    "First Name": "Abizera",
    "Last Name": "Oreste",
    "Code/ID": "RCA0101SHI",
    "Year/Grade": 3,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834845",
  },
  {
    "First Name": "Cyebukayire",
    "Last Name": "Peace",
    "Code/ID": "RCA0103GAK",
    "Year/Grade": 3,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834846",
  },
  {
    "First Name": "Cyusa",
    "Last Name": "Munezero Keny",
    "Code/ID": "RCA0104TGJ",
    "Year/Grade": 3,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834847",
  },
  {
    "First Name": "Dukundane",
    "Last Name": "Daniel",
    "Code/ID": "RCA0105CNX",
    "Year/Grade": 3,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834848",
  },
  {
    "First Name": "Dusengimana",
    "Last Name": "Felix",
    "Code/ID": "RCA0106HQT",
    "Year/Grade": 3,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834849",
  },
  {
    "First Name": "Dushimimana",
    "Last Name": "Samuel",
    "Code/ID": "RCA0107TNP",
    "Year/Grade": 3,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834850",
  },
  {
    "First Name": "Gahamanyi",
    "Last Name": "Yvette",
    "Code/ID": "RCA0108XYB",
    "Year/Grade": 3,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834851",
  },
  {
    "First Name": "Gisa Kaze",
    "Last Name": "Fredson",
    "Code/ID": "RCA0109QNU",
    "Year/Grade": 3,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834852",
  },
  {
    "First Name": "Hagenimana",
    "Last Name": "Yassin",
    "Code/ID": "RCA0110JFX",
    "Year/Grade": 3,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834853",
  },
  {
    "First Name": "Harerimana",
    "Last Name": "Egide",
    "Code/ID": "RCA0111MYG",
    "Year/Grade": 3,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834854",
  },
  {
    "First Name": "Hirwa",
    "Last Name": "Blessing",
    "Code/ID": "RCA0112WBA",
    "Year/Grade": 3,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834855",
  },
  {
    "First Name": "Hirwa Marie -Faustine",
    "Last Name": "Chanelle",
    "Code/ID": "RCA0113MHB",
    "Year/Grade": 3,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834856",
  },
  {
    "First Name": "Igiraneza",
    "Last Name": "Honorine",
    "Code/ID": "RCA0114XBI",
    "Year/Grade": 3,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834857",
  },
  {
    "First Name": "Ikirezi",
    "Last Name": "Ndayambaje Ange Divine",
    "Code/ID": "RCA0115IEW",
    "Year/Grade": 3,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834858",
  },
  {
    "First Name": "Ineza",
    "Last Name": "Aimee Annabelle",
    "Code/ID": "RCA0116GMM",
    "Year/Grade": 3,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834859",
  },
  {
    "First Name": "Ineza",
    "Last Name": "Bella Melissa",
    "Code/ID": "RCA0117AFB",
    "Year/Grade": 3,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834860",
  },
  {
    "First Name": "Inshuti",
    "Last Name": "Joyeuse Souvede",
    "Code/ID": "RCA0118QDX",
    "Year/Grade": 3,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834861",
  },
  {
    "First Name": "Iradukunda",
    "Last Name": "Best Verie",
    "Code/ID": "RCA0119RTL",
    "Year/Grade": 3,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834862",
  },
  {
    "First Name": "Iradukunda",
    "Last Name": "Landrada",
    "Code/ID": "RCA0120KCR",
    "Year/Grade": 3,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834863",
  },
  {
    "First Name": "Iradukunda",
    "Last Name": "Tamara Merlyne",
    "Code/ID": "RCA0121JQP",
    "Year/Grade": 3,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834864",
  },
  {
    "First Name": "Irakiza",
    "Last Name": "Divin",
    "Code/ID": "RCA0122QLR",
    "Year/Grade": 3,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834865",
  },
  {
    "First Name": "Irakoze",
    "Last Name": "Marie Reine Hortance",
    "Code/ID": "RCA0123RZX",
    "Year/Grade": 3,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834866",
  },
  {
    "First Name": "Irakoze Mukezwa",
    "Last Name": "Loraine",
    "Code/ID": "RCA0124TXA",
    "Year/Grade": 3,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834867",
  },
  {
    "First Name": "Irumva",
    "Last Name": "Habumugisha Anselme",
    "Code/ID": "RCA0125BGE",
    "Year/Grade": 3,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834868",
  },
  {
    "First Name": "Ishimwe",
    "Last Name": "Gervais",
    "Code/ID": "RCA0126XMR",
    "Year/Grade": 3,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834869",
  },
  {
    "First Name": "Ishimwe",
    "Last Name": "Marie Pauline",
    "Code/ID": "RCA0127LMW",
    "Year/Grade": 3,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834870",
  },
  {
    "First Name": "Izabayo",
    "Last Name": "Cedric",
    "Code/ID": "RCA0128MDA",
    "Year/Grade": 3,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834871",
  },
  {
    "First Name": "Izere Uwonkunda",
    "Last Name": "Marie Claire Kerie",
    "Code/ID": "RCA0129LUT",
    "Year/Grade": 3,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834872",
  },
  {
    "First Name": "Kobusinge",
    "Last Name": "Shallon",
    "Code/ID": "RCA0130YFW",
    "Year/Grade": 3,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834873",
  },
  {
    "First Name": "Kwizera",
    "Last Name": "Emmanuel",
    "Code/ID": "RCA0131PPM",
    "Year/Grade": 3,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834874",
  },
  {
    "First Name": "Mahoro",
    "Last Name": "Phinah",
    "Code/ID": "RCA0132DFZ",
    "Year/Grade": 3,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834875",
  },
  {
    "First Name": "Makuza",
    "Last Name": "Mugabo Verite",
    "Code/ID": "RCA0133UYX",
    "Year/Grade": 3,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834876",
  },
  {
    "First Name": "Manzi",
    "Last Name": "Gustave",
    "Code/ID": "RCA0134TRW",
    "Year/Grade": 3,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834877",
  },
  {
    "First Name": "Manzi Twahirwa",
    "Last Name": "Mike",
    "Code/ID": "RCA0135USA",
    "Year/Grade": 3,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834878",
  },
  {
    "First Name": "Mfuranziza Sekata",
    "Last Name": "Aimelyse Moss",
    "Code/ID": "RCA0136XRQ",
    "Year/Grade": 3,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834879",
  },
  {
    "First Name": "Mugisha",
    "Last Name": "Edine Noella",
    "Code/ID": "RCA0137QCD",
    "Year/Grade": 3,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834880",
  },
  {
    "First Name": "Mugisha",
    "Last Name": "Isaac",
    "Code/ID": "RCA0138MQG",
    "Year/Grade": 3,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834881",
  },
  {
    "First Name": "Muhodari",
    "Last Name": "Sage",
    "Code/ID": "RCA0139MBA",
    "Year/Grade": 3,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834882",
  },
  {
    "First Name": "Mukundwa",
    "Last Name": "Ange Nicole",
    "Code/ID": "RCA0140GZG",
    "Year/Grade": 3,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834883",
  },
  {
    "First Name": "Munezero",
    "Last Name": "Didier",
    "Code/ID": "RCA0141DNV",
    "Year/Grade": 3,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834884",
  },
  {
    "First Name": "Murenzi",
    "Last Name": "Confiance Tracy",
    "Code/ID": "RCA0142QRB",
    "Year/Grade": 3,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834885",
  },
  {
    "First Name": "Mutoni Uwingeneye",
    "Last Name": "Denyse",
    "Code/ID": "RCA0143PLZ",
    "Year/Grade": 3,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834886",
  },
  {
    "First Name": "Nimuhire",
    "Last Name": "Ange Constance",
    "Code/ID": "RCA0144NFQ",
    "Year/Grade": 3,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834887",
  },
  {
    "First Name": "Niyogitare",
    "Last Name": "Patrick",
    "Code/ID": "RCA0145KXH",
    "Year/Grade": 3,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834888",
  },
  {
    "First Name": "Niyonzima",
    "Last Name": "Stecie",
    "Code/ID": "RCA0146NYZ",
    "Year/Grade": 3,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834889",
  },
  {
    "First Name": "Nsengiyumva",
    "Last Name": "Gershom",
    "Code/ID": "RCA0147DMC",
    "Year/Grade": 3,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834890",
  },
  {
    "First Name": "Nshimiyandinze",
    "Last Name": "Fiston",
    "Code/ID": "RCA0148GZT",
    "Year/Grade": 3,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834891",
  },
  {
    "First Name": "Nshimiye",
    "Last Name": "Emmy",
    "Code/ID": "RCA0149NMU",
    "Year/Grade": 3,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834892",
  },
  {
    "First Name": "Ntakirutimana",
    "Last Name": "Pretty Diane",
    "Code/ID": "RCA0150PTT",
    "Year/Grade": 3,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834893",
  },
  {
    "First Name": "Ntezirizaza",
    "Last Name": "Erneste",
    "Code/ID": "RCA0151VWH",
    "Year/Grade": 3,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834894",
  },
  {
    "First Name": "Ntwari",
    "Last Name": "Clarance Liberiste",
    "Code/ID": "RCA0152RMZ",
    "Year/Grade": 3,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834895",
  },
  {
    "First Name": "Ntwali",
    "Last Name": "Egide",
    "Code/ID": "RCA0153SBK",
    "Year/Grade": 3,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834896",
  },
  {
    "First Name": "Sauve",
    "Last Name": "Jean Luc",
    "Code/ID": "RCA0154RQQ",
    "Year/Grade": 3,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834897",
  },
  {
    "First Name": "Tuyishime",
    "Last Name": "Jean d-Amour",
    "Code/ID": "RCA0155HAP",
    "Year/Grade": 3,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834898",
  },
  {
    "First Name": "Twizeyimana",
    "Last Name": "Elissa",
    "Code/ID": "RCA0156PNM",
    "Year/Grade": 3,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834899",
  },
  {
    "First Name": "Twizeyimana",
    "Last Name": "Jacques",
    "Code/ID": "RCA0157PRZ",
    "Year/Grade": 3,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834900",
  },
  {
    "First Name": "Umuhire",
    "Last Name": "Kellia",
    "Code/ID": "RCA0158RXZ",
    "Year/Grade": 3,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834901",
  },
  {
    "First Name": "Uwababyeyi",
    "Last Name": "Anne Bethiane",
    "Code/ID": "RCA0159JML",
    "Year/Grade": 3,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834902",
  },
  {
    "First Name": "AMIZERO",
    "Last Name": "IRIZA PEACE MARY",
    "Code/ID": "RCA0301BNL",
    "Year/Grade": 1,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834845",
  },
  {
    "First Name": "AMIZERO",
    "Last Name": "NSABIMANA Peace Thierry Tresor",
    "Code/ID": "RCA0302RYZ",
    "Year/Grade": 1,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834846",
  },
  {
    "First Name": "BIGWI",
    "Last Name": "SHYAKA Valentin",
    "Code/ID": "RCA0303NAY",
    "Year/Grade": 1,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834847",
  },
  {
    "First Name": "BIRAMAHIRE",
    "Last Name": "Dan Bellamy",
    "Code/ID": "RCA0304RLE",
    "Year/Grade": 1,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834848",
  },
  {
    "First Name": "BISIZI",
    "Last Name": "MUHIRE Ighor",
    "Code/ID": "RCA0305GUU",
    "Year/Grade": 1,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834849",
  },
  {
    "First Name": "BUGINGO",
    "Last Name": "Elua",
    "Code/ID": "RCA0306WBE",
    "Year/Grade": 1,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834850",
  },
  {
    "First Name": "DUKUNDANE",
    "Last Name": "FURAHA Yves Derick",
    "Code/ID": "RCA0307VLB",
    "Year/Grade": 1,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834851",
  },
  {
    "First Name": "DUSHIME",
    "Last Name": "VALENTIN",
    "Code/ID": "RCA0308MYH",
    "Year/Grade": 1,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834852",
  },
  {
    "First Name": "DUSHIMIYIMANA",
    "Last Name": "Jazzy Bruno",
    "Code/ID": "RCA0309JBM",
    "Year/Grade": 1,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834853",
  },
  {
    "First Name": "GAKUBA",
    "Last Name": "Edmond",
    "Code/ID": "RCA0310LUB",
    "Year/Grade": 1,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834854",
  },
  {
    "First Name": "GISINGIZO",
    "Last Name": "GLORIA",
    "Code/ID": "RCA0311GLU",
    "Year/Grade": 1,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834855",
  },
  {
    "First Name": "HIRWA",
    "Last Name": "GACURABWENGE Vanessa",
    "Code/ID": "RCA0312NJU",
    "Year/Grade": 1,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834856",
  },
  {
    "First Name": "IMANISHIMWE",
    "Last Name": "Emmanuel",
    "Code/ID": "RCA0313GNE",
    "Year/Grade": 1,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834857",
  },
  {
    "First Name": "IMFURA",
    "Last Name": "MURINDA Huguette",
    "Code/ID": "RCA0314PNZ",
    "Year/Grade": 1,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834858",
  },
  {
    "First Name": "INEZA",
    "Last Name": "Axelle",
    "Code/ID": "RCA0315BMN",
    "Year/Grade": 1,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834859",
  },
  {
    "First Name": "INGABIRE",
    "Last Name": "Divine",
    "Code/ID": "RCA0316BVL",
    "Year/Grade": 1,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834860",
  },
  {
    "First Name": "IRADUKUNDA",
    "Last Name": "Mustafa",
    "Code/ID": "RCA0317ZVM",
    "Year/Grade": 1,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834861",
  },
  {
    "First Name": "IRAKARAMA",
    "Last Name": "Laurent",
    "Code/ID": "RCA0318ERM",
    "Year/Grade": 1,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834862",
  },
  {
    "First Name": "IRATUZI",
    "Last Name": "JEHOVA TSIKENI",
    "Code/ID": "RCA0319JML",
    "Year/Grade": 1,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834863",
  },
  {
    "First Name": "ISHIMWE",
    "Last Name": "SUGIRA Yvan",
    "Code/ID": "RCA0320RUL",
    "Year/Grade": 1,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834864",
  },
  {
    "First Name": "ISHIMWE",
    "Last Name": "KEVINE",
    "Code/ID": "RCA0321EMV",
    "Year/Grade": 1,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834865",
  },
  {
    "First Name": "ISHIMWE",
    "Last Name": "VAINQUEUR",
    "Code/ID": "RCA0322RJU",
    "Year/Grade": 1,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834866",
  },
  {
    "First Name": "ISHIMWE NDUNGUTSE",
    "Last Name": "CHARLES",
    "Code/ID": "RCA0323YGU",
    "Year/Grade": 1,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834867",
  },
  {
    "First Name": "ISIMBI",
    "Last Name": "KEZA LYSA",
    "Code/ID": "RCA0324HWP",
    "Year/Grade": 1,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834868",
  },
  {
    "First Name": "KABALISA",
    "Last Name": "Mugisha Melissa",
    "Code/ID": "RCA0325JGW",
    "Year/Grade": 1,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834869",
  },
  {
    "First Name": "KABANDA",
    "Last Name": "MANZI Cedrick",
    "Code/ID": "RCA0326WPU",
    "Year/Grade": 1,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834870",
  },
  {
    "First Name": "KALISA",
    "Last Name": "INEZA Giovanni",
    "Code/ID": "RCA0327GNY",
    "Year/Grade": 1,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834871",
  },
  {
    "First Name": "KARABO",
    "Last Name": "Nadege Diamant",
    "Code/ID": "RCA0328EUB",
    "Year/Grade": 1,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834872",
  },
  {
    "First Name": "KARIGIRWA",
    "Last Name": "Sonia Olga",
    "Code/ID": "RCA0329EMJ",
    "Year/Grade": 1,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834873",
  },
  {
    "First Name": "MAJURA",
    "Last Name": "Anthony Gaudence",
    "Code/ID": "RCA0330ZGV",
    "Year/Grade": 1,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834874",
  },
  {
    "First Name": "MANISHIMWE",
    "Last Name": "YVETTE",
    "Code/ID": "RCA0331UGY",
    "Year/Grade": 1,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834875",
  },
  {
    "First Name": "MANZI",
    "Last Name": "Israel",
    "Code/ID": "RCA0332WHA",
    "Year/Grade": 1,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834876",
  },
  {
    "First Name": "MUGISHA",
    "Last Name": "PUCEAU PRECIEUX",
    "Code/ID": "RCA0333RLN",
    "Year/Grade": 1,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834877",
  },
  {
    "First Name": "MUGISHA",
    "Last Name": "DORCUS",
    "Code/ID": "RCA0334EBU",
    "Year/Grade": 1,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834878",
  },
  {
    "First Name": "MURANGWA",
    "Last Name": "PACIFIQUE",
    "Code/ID": "RCA0335ARW",
    "Year/Grade": 1,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834879",
  },
  {
    "First Name": "MUTESA",
    "Last Name": "CEDRIC",
    "Code/ID": "RCA0336JBN",
    "Year/Grade": 1,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834880",
  },
  {
    "First Name": "MUTUYIMANA",
    "Last Name": "JOYEUSE RITA",
    "Code/ID": "RCA0337VBP",
    "Year/Grade": 1,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834881",
  },
  {
    "First Name": "MWENEDATA",
    "Last Name": "Apotre",
    "Code/ID": "RCA0338BEZ",
    "Year/Grade": 1,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834882",
  },
  {
    "First Name": "NDAYAMBAJE",
    "Last Name": "Patrick",
    "Code/ID": "RCA0339WNM",
    "Year/Grade": 1,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834883",
  },
  {
    "First Name": "NDAYISHIMIYE",
    "Last Name": "GILBERT",
    "Code/ID": "RCA0340WLW",
    "Year/Grade": 1,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834884",
  },
  {
    "First Name": "NDIZIHIWE",
    "Last Name": "REGIS",
    "Code/ID": "RCA0341UUJ",
    "Year/Grade": 1,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834885",
  },
  {
    "First Name": "Ngabo",
    "Last Name": "Iris",
    "Code/ID": "RCA0342LEZ",
    "Year/Grade": 1,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834886",
  },
  {
    "First Name": "NIBAKURE",
    "Last Name": "Josephine",
    "Code/ID": "RCA0343RWW",
    "Year/Grade": 1,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834887",
  },
  {
    "First Name": "NIYIDUHUMUGISHA",
    "Last Name": "EDEN",
    "Code/ID": "RCA0344AUP",
    "Year/Grade": 1,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834888",
  },
  {
    "First Name": "NIYOMUNGELI",
    "Last Name": "ALINE",
    "Code/ID": "RCA0345RMR",
    "Year/Grade": 1,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834889",
  },
  {
    "First Name": "NIYONSENGA",
    "Last Name": "VALENS",
    "Code/ID": "RCA0346RAP",
    "Year/Grade": 1,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834890",
  },
  {
    "First Name": "NKUBITOYIMANZI",
    "Last Name": "RUTH",
    "Code/ID": "RCA0347EBP",
    "Year/Grade": 1,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834891",
  },
  {
    "First Name": "Nyishimente",
    "Last Name": "Lois",
    "Code/ID": "RCA0348MUU",
    "Year/Grade": 1,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834892",
  },
  {
    "First Name": "NZAMBAZAMARIYA",
    "Last Name": "ROSINE",
    "Code/ID": "RCA0349JVW",
    "Year/Grade": 1,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834893",
  },
  {
    "First Name": "RUKUNDO",
    "Last Name": "HONORE",
    "Code/ID": "RCA0350JHJ",
    "Year/Grade": 1,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834894",
  },
  {
    "First Name": "RUTAGENGWA",
    "Last Name": "ASANTE BRUCE",
    "Code/ID": "RCA0351YHG",
    "Year/Grade": 1,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834895",
  },
  {
    "First Name": "UJENEZA",
    "Last Name": "DIVINE",
    "Code/ID": "RCA0352ERR",
    "Year/Grade": 1,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834896",
  },
  {
    "First Name": "UMUGWANEZA",
    "Last Name": "Alice",
    "Code/ID": "RCA0353ANU",
    "Year/Grade": 1,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834897",
  },
  {
    "First Name": "UMUGWANEZA",
    "Last Name": "ANAISE",
    "Code/ID": "RCA0354JNL",
    "Year/Grade": 1,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834898",
  },
  {
    "First Name": "UMUTONI",
    "Last Name": "MIREILLE",
    "Code/ID": "RCA0355HGN",
    "Year/Grade": 1,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834899",
  },
  {
    "First Name": "UMWALI",
    "Last Name": "Cynthia",
    "Code/ID": "RCA0356RHB",
    "Year/Grade": 1,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834900",
  },
  {
    "First Name": "UNYUZIMFURA",
    "Last Name": "ISHIMWE JOY KEVIN",
    "Code/ID": "RCA0357YAB",
    "Year/Grade": 1,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834901",
  },
  {
    "First Name": "USHIMIRWA",
    "Last Name": "INGABIRE BENITHA",
    "Code/ID": "RCA0358MYV",
    "Year/Grade": 1,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834902",
  },
  {
    "First Name": "UWASE",
    "Last Name": "Lina",
    "Code/ID": "RCA0359AHW",
    "Year/Grade": 1,
    Class: "A",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834903",
  },
  {
    "First Name": "UWIRINGIYIMANA",
    "Last Name": "MARTHE",
    "Code/ID": "RCA0360MAW",
    "Year/Grade": 1,
    Class: "B",
    "Parent Email(s)": "precieuxmugisha@gmail.com, undimubyeyi@gmail.com",
    "Parent Tel(s)": "0782307144, 0788834904",
  },
];

export const AllEducatorsDisplay: EducatorObject[] = [
  {
    "firstName": "HABANABASHAKA",
    "lastName": "Jean Damascene",
    "IdNumber": "9039412014726744",
    "lessons": [
      "PHP",
      "WUI",
      "DSA"
    ],
    "telephone": "0788509298",
    "code": "RCA180EDU",
    "email": "RCA51@gmail.com"
  },
  {
    "firstName": "INGABO",
    "lastName": "Celestin",
    "IdNumber": "3419797497913099",
    "lessons": [
      "ADN"
    ],
    "telephone": "078835788",
    "code": "RCA515EDU",
    "email": "RCA99@gmail.com"
  },
  {
    "firstName": "HABANABASHAKA",
    "lastName": "Jean De Dieu",
    "IdNumber": "2134617654858136",
    "lessons": [
      "PHY"
    ],
    "telephone": "0788168530",
    "code": "RCA284EDU",
    "email": "RCA65@gmail.com"
  },
  {
    "firstName": "RWAGAJU",
    "lastName": "Aphrodice",
    "IdNumber": "4797043337420890",
    "lessons": [
      "FOP",
      "OOP"
    ],
    "telephone": "0788278758",
    "code": "RCA126EDU",
    "email": "RCA93@gmail.com"
  },
  {
    "firstName": "HATANGIMBABAZI",
    "lastName": "Hilaire",
    "IdNumber": "3288811064231326",
    "lessons": [
      "SAD",
      "BON"
    ],
    "telephone": "0788180646",
    "code": "RCA41EDU",
    "email": "RCA21@gmail.com"
  },
  {
    "firstName": "MWIZERWA",
    "lastName": "Stanley",
    "IdNumber": "3443613271781011",
    "lessons": [
      "MOD",
      "WJS"
    ],
    "telephone": "0788621513",
    "code": "RCA94EDU",
    "email": "RCA32@gmail.com"
  },
  {
    "firstName": "KAROMBA",
    "lastName": "Benon",
    "IdNumber": "602979575321454",
    "lessons": [],
    "telephone": "0788237202",
    "code": "RCA101EDU",
    "email": "RCA28@gmail.com"
  },
  {
    "firstName": "MUKASHEMA",
    "lastName": "Benilde",
    "IdNumber": "4259344791841653",
    "lessons": [],
    "telephone": "0788845870",
    "code": "RCA792EDU",
    "email": "RCA78@gmail.com"
  },
  {
    "firstName": "MUGANGA",
    "lastName": "Utazwi Izina",
    "IdNumber": "7118022887217772",
    "lessons": [],
    "telephone": "0788532087",
    "code": "RCA445EDU",
    "email": "RCA41@gmail.com"
  },
  {
    "firstName": "NSABYIMANA",
    "lastName": "Egide",
    "IdNumber": "5186660208044240",
    "lessons": [
      "MOD",
      "WJS"
    ],
    "telephone": "0788452758",
    "code": "RCA874EDU",
    "email": "RCA34@gmail.com"
  },
  {
    "firstName": "UWITONZE",
    "lastName": "Jean Bosco",
    "IdNumber": "6473271442151459",
    "lessons": [
      "MTC"
    ],
    "telephone": "0788480589",
    "code": "RCA168EDU",
    "email": "RCA12@gmail.com"
  },
  {
    "firstName": "BAZIRIMWABO",
    "lastName": "Gabriel",
    "IdNumber": "2217932018981972",
    "lessons": [
      "EMB"
    ],
    "telephone": "0788195385",
    "code": "RCA249EDU",
    "email": "RCA22@gmail.com"
  }
]

export const years = [
  {
    name: "Year 1",
    value: "year_1",
  },
  {
    name: "Year 2",
    value: "year_2",
  },
  {
    name: "Year 3",
    value: "year_3",
  },
];
export const classes = [
  {
    name: "A",
    value: "A",
  },
  {
    name: "B",
    value: "B",
  },
  {
    name: "C",
    value: "C",
  },
];

export const announcementsFaker: AnnouncementObject[] = [
  {
    heading: "Discipline issues",
    content:
      "The students are starting to behave very wrong. I think that the parents should allows us to beat the shit out there children!",
    posted: 1666534238354,
    postedBy: "Jean Damascene Habanabashaka",
  },
  {
    heading: "Teacher talk",
    content:
      "Dukeneye ko abarimu bajya batanga works nyinshi cyane rwose, Murabyumva mute??",
    posted: 1666534238354,
    postedBy: "Stanley Mwizerwa",
  },
  {
    heading: "Parents Please!!!",
    content:
      "Mwa babyeyo mwe mwakohereje abana banyu bagatangira igihembwe hakiri kare, nibarenza ejo bataraza mugomba kubaherekeza",
    posted: 1666534238354,
    postedBy: "Nsabyimana Egide",
  },
];
